###########################################################
# +-----------------------------------------------------+ #
# |                      Settings                       | #
# +-----------------------------------------------------+ #
###########################################################

players:
   # When you die, you loose money.
   death: 10
   kill: 25

mobs:
   blaze: 18.0
   cave-spider: 15.0
   creeper: 15.0
   enderman: 20.0
   endermite: 20.0
   ender-dragon: 150.0
   ghast: 25.0
   giant: 80.0
   guardian: 100.0
   magma-cube: 3.0
   pig-zombie: 12.0
   shulker: 18.0
   silverfish: 13.0
   skeleton: 8.0
   slime: 3.0
   spider: 8.0
   witch: 20.0
   wither: 100.0
   wither-skeleton: 15.0
   zombie: 8.0

enabled:
   blaze: true
   cave-spider: true
   creeper: true
   enderman: true
   endermite: true
   ender-dragon: true
   ghast: true
   giant: true
   guardian: true
   magma-cube: true
   pig-zombie: true
   player-death: true
   player-kill: true
   shulker: true
   silverfish: true
   skeleton: true
   slime: true
   spider: true
   witch: true
   wither: true
   wither-skeleton: true
   zombie: true
