name: MobsReward
main: fr.plx0wn.MobsReward
depend: [Vault]
author: [lucluc52, Plx0wn]
version: 0.4

commands:
   rewards:
      default: op
      description: Main command.
permissions:
   rewards.admin:
      default: op
      description: Allow players to use admin commands.
   rewards.all:
      default: op
      description: Allow players to get rewards with all entities.
      children:
         rewards.mobs.*: true
         rewards.neutrals.*: true
         rewards.players.*: true
